[package]
name = "app"
version = "0.0.1"
authors = ["Keisuke Kan <9renpoto+g59@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook"]
